# Generated by Django 3.2.8 on 2021-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='stack',
            field=models.CharField(choices=[('Front', 'Front'), ('Back', 'Back')], default='Front', max_length=5),
        ),
    ]
