# Generated by Django 3.2.8 on 2021-10-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sub_title',
            new_name='categories',
        ),
    ]
